sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
language: node_js
node_js: stable
os:
  - osx
branches:
  only:
    - master # build master branch only
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn docs:build
notifications:
  slack:
    if: branch = master
  email:
    recipients:
      - hejianxian@foreverht.com
    on_success: change
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs/.vuepress/dist/
  on:
    branch: master  
    