sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
language: node_js
node_js: stable
os:
  - osx
branches:
  only:
    - master # build master branch only
install:
  - yarn
script:
  - yarn lint
  - yarn build
notifications:
  slack:
    if: branch = master
  email:
    recipients:
      - hejianxian@foreverht.com
    on_success: change
    on_failure: always

    